/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page_1;
    QPushButton *nextButton;
    QGroupBox *nameGroupBox;
    QPlainTextEdit *firstNameText;
    QPlainTextEdit *lastNameText;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *guestLabel;
    QGroupBox *groupBox;
    QLabel *label_6;
    QLabel *label_7;
    QRadioButton *sQueenRadioButton;
    QRadioButton *sKingRadioButton;
    QRadioButton *aQueenRadioButton;
    QRadioButton *aKingRadioButton;
    QFrame *line;
    QGroupBox *checkIngroupBox;
    QLabel *label;
    QDateEdit *dateEdit;
    QLabel *label_2;
    QSpinBox *dateLengthSpinBox;
    QLabel *label_3;
    QSpinBox *guestSpinBox;
    QLabel *label_4;
    QSpinBox *childrenSpinbox;
    QCheckBox *parkingCheckBox;
    QLabel *label_20;
    QGroupBox *groupBox_3;
    QLabel *totalEstimateLabel;
    QStackedWidget *stackedWidget2;
    QWidget *page;
    QLabel *imageLabel1;
    QLabel *label_25;
    QWidget *page_3;
    QLabel *imageLabel2;
    QLabel *label_22;
    QPushButton *rightArrowButton;
    QPushButton *leftArrorwButton;
    QLabel *label_21;
    QLabel *label_19;
    QWidget *page_2;
    QGroupBox *summaryGroupBox;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *roomTypeLabel;
    QLabel *taxLabel;
    QLabel *parkingFeeLabel;
    QLabel *totalDueLabel;
    QLabel *label_5;
    QLabel *resortFeeLabel;
    QFrame *line_2;
    QLabel *label_23;
    QGroupBox *paymentGroupBox;
    QRadioButton *masterCardButton;
    QRadioButton *visaButton;
    QRadioButton *americanButton;
    QRadioButton *discoverButton;
    QLineEdit *creditCardLineEdit;
    QLabel *label_12;
    QLabel *label_13;
    QComboBox *monthComboBox;
    QComboBox *yearComboBox;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_24;
    QPushButton *confirmButton;
    QPushButton *backButton;
    QPushButton *exitButton;
    QStatusBar *statusbar;
    QMenuBar *menubar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(797, 487);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 801, 461));
        stackedWidget->setStyleSheet(QString::fromUtf8("background-color:rgb(230, 230, 230);"));
        stackedWidget->setFrameShadow(QFrame::Raised);
        page_1 = new QWidget();
        page_1->setObjectName(QString::fromUtf8("page_1"));
        nextButton = new QPushButton(page_1);
        nextButton->setObjectName(QString::fromUtf8("nextButton"));
        nextButton->setGeometry(QRect(430, 420, 51, 21));
        nextButton->setCursor(QCursor(Qt::PointingHandCursor));
        nextButton->setStyleSheet(QString::fromUtf8("border: none;"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/button_next(1).png"), QSize(), QIcon::Normal, QIcon::Off);
        nextButton->setIcon(icon);
        nextButton->setIconSize(QSize(50, 32));
        nameGroupBox = new QGroupBox(page_1);
        nameGroupBox->setObjectName(QString::fromUtf8("nameGroupBox"));
        nameGroupBox->setGeometry(QRect(20, 20, 381, 101));
        nameGroupBox->setStyleSheet(QString::fromUtf8(""));
        firstNameText = new QPlainTextEdit(nameGroupBox);
        firstNameText->setObjectName(QString::fromUtf8("firstNameText"));
        firstNameText->setGeometry(QRect(10, 50, 161, 31));
        firstNameText->setFocusPolicy(Qt::StrongFocus);
        firstNameText->setStyleSheet(QString::fromUtf8(""));
        firstNameText->setFrameShape(QFrame::Panel);
        firstNameText->setFrameShadow(QFrame::Sunken);
        firstNameText->setTabChangesFocus(true);
        lastNameText = new QPlainTextEdit(nameGroupBox);
        lastNameText->setObjectName(QString::fromUtf8("lastNameText"));
        lastNameText->setGeometry(QRect(200, 50, 171, 31));
        lastNameText->setFocusPolicy(Qt::StrongFocus);
        lastNameText->setStyleSheet(QString::fromUtf8(""));
        lastNameText->setFrameShape(QFrame::Panel);
        lastNameText->setFrameShadow(QFrame::Sunken);
        lastNameText->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        lastNameText->setTabChangesFocus(true);
        lastNameText->setBackgroundVisible(false);
        label_16 = new QLabel(nameGroupBox);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 30, 91, 16));
        label_16->setStyleSheet(QString::fromUtf8("border: none;"));
        label_17 = new QLabel(nameGroupBox);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(200, 30, 61, 16));
        label_17->setStyleSheet(QString::fromUtf8("border: none"));
        guestLabel = new QLabel(nameGroupBox);
        guestLabel->setObjectName(QString::fromUtf8("guestLabel"));
        guestLabel->setGeometry(QRect(130, 0, 131, 20));
        QFont font;
        font.setFamily(QString::fromUtf8("Garamond"));
        font.setPointSize(12);
        font.setBold(true);
        font.setUnderline(true);
        font.setWeight(75);
        guestLabel->setFont(font);
        guestLabel->setFrameShape(QFrame::NoFrame);
        guestLabel->setFrameShadow(QFrame::Sunken);
        groupBox = new QGroupBox(page_1);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(20, 130, 381, 111));
        groupBox->setStyleSheet(QString::fromUtf8(""));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(70, 30, 61, 16));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Garamond"));
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setItalic(false);
        font1.setWeight(75);
        label_6->setFont(font1);
        label_6->setStyleSheet(QString::fromUtf8("border: none;"));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(260, 30, 47, 14));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Garamond"));
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        label_7->setFont(font2);
        label_7->setStyleSheet(QString::fromUtf8("border: none;"));
        sQueenRadioButton = new QRadioButton(groupBox);
        sQueenRadioButton->setObjectName(QString::fromUtf8("sQueenRadioButton"));
        sQueenRadioButton->setGeometry(QRect(10, 50, 181, 18));
        sQueenRadioButton->setStyleSheet(QString::fromUtf8("border: none;"));
        sQueenRadioButton->setCheckable(true);
        sQueenRadioButton->setAutoExclusive(true);
        sKingRadioButton = new QRadioButton(groupBox);
        sKingRadioButton->setObjectName(QString::fromUtf8("sKingRadioButton"));
        sKingRadioButton->setGeometry(QRect(10, 80, 181, 18));
        sKingRadioButton->setStyleSheet(QString::fromUtf8("border: none;"));
        sKingRadioButton->setCheckable(true);
        sKingRadioButton->setAutoExclusive(true);
        aQueenRadioButton = new QRadioButton(groupBox);
        aQueenRadioButton->setObjectName(QString::fromUtf8("aQueenRadioButton"));
        aQueenRadioButton->setGeometry(QRect(200, 50, 181, 18));
        aQueenRadioButton->setStyleSheet(QString::fromUtf8("border: none;"));
        aQueenRadioButton->setAutoExclusive(true);
        aKingRadioButton = new QRadioButton(groupBox);
        aKingRadioButton->setObjectName(QString::fromUtf8("aKingRadioButton"));
        aKingRadioButton->setGeometry(QRect(200, 80, 171, 18));
        aKingRadioButton->setStyleSheet(QString::fromUtf8("border: none;"));
        aKingRadioButton->setAutoExclusive(true);
        line = new QFrame(groupBox);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(180, 30, 20, 71));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        checkIngroupBox = new QGroupBox(page_1);
        checkIngroupBox->setObjectName(QString::fromUtf8("checkIngroupBox"));
        checkIngroupBox->setGeometry(QRect(20, 250, 381, 141));
        checkIngroupBox->setStyleSheet(QString::fromUtf8(""));
        label = new QLabel(checkIngroupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 20, 101, 41));
        label->setStyleSheet(QString::fromUtf8("border: none;"));
        dateEdit = new QDateEdit(checkIngroupBox);
        dateEdit->setObjectName(QString::fromUtf8("dateEdit"));
        dateEdit->setGeometry(QRect(20, 50, 121, 21));
        dateEdit->setStyleSheet(QString::fromUtf8("color:black;"));
        dateEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        dateEdit->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        dateEdit->setMinimumDateTime(QDateTime(QDate(1752, 9, 14), QTime(0, 0, 0)));
        dateEdit->setCalendarPopup(true);
        dateEdit->setCurrentSectionIndex(0);
        label_2 = new QLabel(checkIngroupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(210, 20, 101, 41));
        label_2->setStyleSheet(QString::fromUtf8("border: none;"));
        dateLengthSpinBox = new QSpinBox(checkIngroupBox);
        dateLengthSpinBox->setObjectName(QString::fromUtf8("dateLengthSpinBox"));
        dateLengthSpinBox->setGeometry(QRect(210, 50, 42, 21));
        dateLengthSpinBox->setStyleSheet(QString::fromUtf8(""));
        dateLengthSpinBox->setMinimum(1);
        dateLengthSpinBox->setMaximum(7);
        label_3 = new QLabel(checkIngroupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(20, 80, 41, 21));
        label_3->setStyleSheet(QString::fromUtf8("border: none;"));
        guestSpinBox = new QSpinBox(checkIngroupBox);
        guestSpinBox->setObjectName(QString::fromUtf8("guestSpinBox"));
        guestSpinBox->setGeometry(QRect(20, 100, 41, 21));
        guestSpinBox->setStyleSheet(QString::fromUtf8(""));
        guestSpinBox->setMinimum(1);
        label_4 = new QLabel(checkIngroupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(100, 80, 41, 20));
        label_4->setStyleSheet(QString::fromUtf8("border: none;"));
        childrenSpinbox = new QSpinBox(checkIngroupBox);
        childrenSpinbox->setObjectName(QString::fromUtf8("childrenSpinbox"));
        childrenSpinbox->setGeometry(QRect(100, 100, 41, 21));
        childrenSpinbox->setStyleSheet(QString::fromUtf8(""));
        parkingCheckBox = new QCheckBox(checkIngroupBox);
        parkingCheckBox->setObjectName(QString::fromUtf8("parkingCheckBox"));
        parkingCheckBox->setGeometry(QRect(210, 100, 171, 21));
        parkingCheckBox->setStyleSheet(QString::fromUtf8("border: none;"));
        label_20 = new QLabel(checkIngroupBox);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(120, -10, 161, 41));
        label_20->setFont(font);
        label_20->setStyleSheet(QString::fromUtf8("border: none;"));
        label_20->setFrameShape(QFrame::NoFrame);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setLineWidth(0);
        groupBox_3 = new QGroupBox(page_1);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(280, 400, 121, 41));
        groupBox_3->setStyleSheet(QString::fromUtf8(""));
        totalEstimateLabel = new QLabel(groupBox_3);
        totalEstimateLabel->setObjectName(QString::fromUtf8("totalEstimateLabel"));
        totalEstimateLabel->setGeometry(QRect(10, 10, 101, 21));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Garamond"));
        font3.setPointSize(12);
        totalEstimateLabel->setFont(font3);
        totalEstimateLabel->setLayoutDirection(Qt::RightToLeft);
        totalEstimateLabel->setStyleSheet(QString::fromUtf8("border: none;"));
        totalEstimateLabel->setFrameShape(QFrame::NoFrame);
        totalEstimateLabel->setAlignment(Qt::AlignCenter);
        stackedWidget2 = new QStackedWidget(page_1);
        stackedWidget2->setObjectName(QString::fromUtf8("stackedWidget2"));
        stackedWidget2->setGeometry(QRect(410, 10, 381, 311));
        stackedWidget2->setFrameShadow(QFrame::Raised);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        imageLabel1 = new QLabel(page);
        imageLabel1->setObjectName(QString::fromUtf8("imageLabel1"));
        imageLabel1->setGeometry(QRect(20, 10, 341, 261));
        imageLabel1->setStyleSheet(QString::fromUtf8(""));
        imageLabel1->setFrameShape(QFrame::Box);
        imageLabel1->setFrameShadow(QFrame::Raised);
        label_25 = new QLabel(page);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(150, 280, 91, 21));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Calibri"));
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        label_25->setFont(font4);
        stackedWidget2->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        imageLabel2 = new QLabel(page_3);
        imageLabel2->setObjectName(QString::fromUtf8("imageLabel2"));
        imageLabel2->setGeometry(QRect(20, 10, 341, 261));
        imageLabel2->setFrameShape(QFrame::Box);
        imageLabel2->setFrameShadow(QFrame::Raised);
        label_22 = new QLabel(page_3);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(150, 280, 81, 21));
        label_22->setFont(font4);
        stackedWidget2->addWidget(page_3);
        rightArrowButton = new QPushButton(page_1);
        rightArrowButton->setObjectName(QString::fromUtf8("rightArrowButton"));
        rightArrowButton->setGeometry(QRect(750, 290, 21, 20));
        rightArrowButton->setCursor(QCursor(Qt::PointingHandCursor));
        rightArrowButton->setStyleSheet(QString::fromUtf8("border: none;"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/images/img_71732.png"), QSize(), QIcon::Normal, QIcon::Off);
        rightArrowButton->setIcon(icon1);
        rightArrowButton->setIconSize(QSize(9, 20));
        leftArrorwButton = new QPushButton(page_1);
        leftArrorwButton->setObjectName(QString::fromUtf8("leftArrorwButton"));
        leftArrorwButton->setGeometry(QRect(430, 290, 21, 20));
        leftArrorwButton->setCursor(QCursor(Qt::PointingHandCursor));
        leftArrorwButton->setStyleSheet(QString::fromUtf8("border: none;;"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/images/60775.png"), QSize(), QIcon::Normal, QIcon::Off);
        leftArrorwButton->setIcon(icon2);
        leftArrorwButton->setIconSize(QSize(15, 32));
        label_21 = new QLabel(page_1);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(30, 400, 241, 41));
        label_21->setFont(font);
        label_21->setStyleSheet(QString::fromUtf8("border: none;"));
        label_21->setFrameShape(QFrame::NoFrame);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setLineWidth(0);
        label_19 = new QLabel(page_1);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(170, 131, 101, 20));
        label_19->setFont(font);
        label_19->setStyleSheet(QString::fromUtf8("border: none;"));
        label_19->setFrameShape(QFrame::NoFrame);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setLineWidth(0);
        stackedWidget->addWidget(page_1);
        nextButton->raise();
        groupBox->raise();
        checkIngroupBox->raise();
        groupBox_3->raise();
        stackedWidget2->raise();
        rightArrowButton->raise();
        leftArrorwButton->raise();
        nameGroupBox->raise();
        label_21->raise();
        label_19->raise();
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        summaryGroupBox = new QGroupBox(page_2);
        summaryGroupBox->setObjectName(QString::fromUtf8("summaryGroupBox"));
        summaryGroupBox->setGeometry(QRect(30, 20, 531, 181));
        label_8 = new QLabel(summaryGroupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 30, 61, 31));
        label_9 = new QLabel(summaryGroupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 50, 31, 41));
        label_10 = new QLabel(summaryGroupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 80, 61, 31));
        label_11 = new QLabel(summaryGroupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 150, 51, 31));
        roomTypeLabel = new QLabel(summaryGroupBox);
        roomTypeLabel->setObjectName(QString::fromUtf8("roomTypeLabel"));
        roomTypeLabel->setGeometry(QRect(360, 30, 151, 21));
        roomTypeLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        taxLabel = new QLabel(summaryGroupBox);
        taxLabel->setObjectName(QString::fromUtf8("taxLabel"));
        taxLabel->setGeometry(QRect(360, 60, 151, 20));
        taxLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parkingFeeLabel = new QLabel(summaryGroupBox);
        parkingFeeLabel->setObjectName(QString::fromUtf8("parkingFeeLabel"));
        parkingFeeLabel->setGeometry(QRect(360, 80, 151, 31));
        parkingFeeLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        totalDueLabel = new QLabel(summaryGroupBox);
        totalDueLabel->setObjectName(QString::fromUtf8("totalDueLabel"));
        totalDueLabel->setGeometry(QRect(360, 150, 151, 20));
        totalDueLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_5 = new QLabel(summaryGroupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 110, 61, 21));
        resortFeeLabel = new QLabel(summaryGroupBox);
        resortFeeLabel->setObjectName(QString::fromUtf8("resortFeeLabel"));
        resortFeeLabel->setGeometry(QRect(360, 110, 151, 16));
        resortFeeLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line_2 = new QFrame(summaryGroupBox);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(10, 140, 511, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_23 = new QLabel(summaryGroupBox);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(160, 10, 201, 21));
        label_23->setFont(font);
        paymentGroupBox = new QGroupBox(page_2);
        paymentGroupBox->setObjectName(QString::fromUtf8("paymentGroupBox"));
        paymentGroupBox->setGeometry(QRect(30, 220, 531, 171));
        QFont font5;
        font5.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font5.setPointSize(8);
        font5.setBold(false);
        font5.setWeight(50);
        paymentGroupBox->setFont(font5);
        paymentGroupBox->setCheckable(false);
        paymentGroupBox->setChecked(false);
        masterCardButton = new QRadioButton(paymentGroupBox);
        masterCardButton->setObjectName(QString::fromUtf8("masterCardButton"));
        masterCardButton->setGeometry(QRect(10, 40, 111, 18));
        masterCardButton->setFont(font5);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/images/master.png"), QSize(), QIcon::Normal, QIcon::Off);
        masterCardButton->setIcon(icon3);
        masterCardButton->setIconSize(QSize(32, 32));
        masterCardButton->setCheckable(true);
        masterCardButton->setChecked(false);
        visaButton = new QRadioButton(paymentGroupBox);
        visaButton->setObjectName(QString::fromUtf8("visaButton"));
        visaButton->setGeometry(QRect(140, 40, 83, 18));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/images/visa.png"), QSize(), QIcon::Normal, QIcon::Off);
        visaButton->setIcon(icon4);
        visaButton->setIconSize(QSize(32, 32));
        americanButton = new QRadioButton(paymentGroupBox);
        americanButton->setObjectName(QString::fromUtf8("americanButton"));
        americanButton->setGeometry(QRect(240, 40, 141, 18));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/images/american.png"), QSize(), QIcon::Normal, QIcon::Off);
        americanButton->setIcon(icon5);
        americanButton->setIconSize(QSize(32, 32));
        discoverButton = new QRadioButton(paymentGroupBox);
        discoverButton->setObjectName(QString::fromUtf8("discoverButton"));
        discoverButton->setGeometry(QRect(410, 40, 101, 18));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/images/discover.png"), QSize(), QIcon::Normal, QIcon::Off);
        discoverButton->setIcon(icon6);
        discoverButton->setIconSize(QSize(32, 32));
        creditCardLineEdit = new QLineEdit(paymentGroupBox);
        creditCardLineEdit->setObjectName(QString::fromUtf8("creditCardLineEdit"));
        creditCardLineEdit->setGeometry(QRect(130, 70, 311, 31));
        label_12 = new QLabel(paymentGroupBox);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(130, 101, 47, 20));
        label_13 = new QLabel(paymentGroupBox);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(200, 101, 47, 20));
        monthComboBox = new QComboBox(paymentGroupBox);
        monthComboBox->setObjectName(QString::fromUtf8("monthComboBox"));
        monthComboBox->setGeometry(QRect(130, 120, 51, 22));
        yearComboBox = new QComboBox(paymentGroupBox);
        yearComboBox->setObjectName(QString::fromUtf8("yearComboBox"));
        yearComboBox->setGeometry(QRect(200, 120, 61, 22));
        label_14 = new QLabel(paymentGroupBox);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 80, 111, 16));
        label_15 = new QLabel(paymentGroupBox);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(30, 120, 91, 20));
        label_24 = new QLabel(paymentGroupBox);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(180, 5, 151, 21));
        label_24->setFont(font);
        confirmButton = new QPushButton(page_2);
        confirmButton->setObjectName(QString::fromUtf8("confirmButton"));
        confirmButton->setGeometry(QRect(390, 410, 101, 20));
        confirmButton->setStyleSheet(QString::fromUtf8("border: none;"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/images/button_confirm-pay(1).png"), QSize(), QIcon::Normal, QIcon::Off);
        confirmButton->setIcon(icon7);
        confirmButton->setIconSize(QSize(100, 32));
        backButton = new QPushButton(page_2);
        backButton->setObjectName(QString::fromUtf8("backButton"));
        backButton->setGeometry(QRect(320, 410, 51, 20));
        backButton->setLayoutDirection(Qt::LeftToRight);
        backButton->setStyleSheet(QString::fromUtf8("border: none;"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/images/button_back(1).png"), QSize(), QIcon::Normal, QIcon::Off);
        backButton->setIcon(icon8);
        backButton->setIconSize(QSize(48, 32));
        exitButton = new QPushButton(page_2);
        exitButton->setObjectName(QString::fromUtf8("exitButton"));
        exitButton->setGeometry(QRect(510, 410, 51, 20));
        exitButton->setStyleSheet(QString::fromUtf8("border: none;"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/images/button_exit(1).png"), QSize(), QIcon::Normal, QIcon::Off);
        exitButton->setIcon(icon9);
        exitButton->setIconSize(QSize(48, 32));
        stackedWidget->addWidget(page_2);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 797, 22));
        MainWindow->setMenuBar(menubar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);
        stackedWidget2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        nextButton->setText(QString());
        nameGroupBox->setTitle(QString());
        label_16->setText(QApplication::translate("MainWindow", "First name", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Last name", nullptr));
        guestLabel->setText(QApplication::translate("MainWindow", "Guest Information", nullptr));
        groupBox->setTitle(QString());
        label_6->setText(QApplication::translate("MainWindow", "*Standard", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "*Atrium", nullptr));
        sQueenRadioButton->setText(QApplication::translate("MainWindow", "2-Queen Bedroom ($284/night)", nullptr));
        sKingRadioButton->setText(QApplication::translate("MainWindow", "1-King Bedroom ($290/night)", nullptr));
        aQueenRadioButton->setText(QApplication::translate("MainWindow", "2-Queen Bedroom ($325/night)", nullptr));
        aKingRadioButton->setText(QApplication::translate("MainWindow", "1-King Bedroom ($350/night)", nullptr));
        checkIngroupBox->setTitle(QString());
        label->setText(QApplication::translate("MainWindow", "Check-in Date:", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Number of nights:", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Guests:", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Children:", nullptr));
        parkingCheckBox->setText(QApplication::translate("MainWindow", "Vehicle Parking ($12.75/night)", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Check-in Information", nullptr));
        groupBox_3->setTitle(QString());
        totalEstimateLabel->setText(QString());
        imageLabel1->setText(QString());
        label_25->setText(QApplication::translate("MainWindow", "Room Preview", nullptr));
        imageLabel2->setText(QString());
        label_22->setText(QApplication::translate("MainWindow", "Room Preview", nullptr));
        rightArrowButton->setText(QString());
        leftArrorwButton->setText(QString());
        label_21->setText(QApplication::translate("MainWindow", "Total Estimate before tax and fees: ", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "Room Type", nullptr));
        summaryGroupBox->setTitle(QString());
        label_8->setText(QApplication::translate("MainWindow", "Room Type:", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Tax:", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Parking fee: ", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Total due: ", nullptr));
        roomTypeLabel->setText(QString());
        taxLabel->setText(QString());
        parkingFeeLabel->setText(QString());
        totalDueLabel->setText(QString());
        label_5->setText(QApplication::translate("MainWindow", "Resort fee:", nullptr));
        resortFeeLabel->setText(QString());
        label_23->setText(QApplication::translate("MainWindow", "Summary of Charges (USD)", nullptr));
        paymentGroupBox->setTitle(QString());
        masterCardButton->setText(QApplication::translate("MainWindow", "Mastercard", nullptr));
        visaButton->setText(QApplication::translate("MainWindow", "Visa", nullptr));
        americanButton->setText(QApplication::translate("MainWindow", "American Express", nullptr));
        discoverButton->setText(QApplication::translate("MainWindow", "Discover", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "MM", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "YYYY", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Credit Card Number:", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "Expiration Date:", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Payment Information", nullptr));
        confirmButton->setText(QString());
        backButton->setText(QString());
        exitButton->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
